name: Build
on:
  pull_request:
    paths-ignore:
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Set up Nix
        uses: $/.github/actions/setup
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build the Go package
        run: nix build -L
